//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio
    {
        public int IdPremio { get; set; }
        public int Cantidad { get; set; }
        public string Anio { get; set; }
        public int IdCompetidor { get; set; }
    
        public virtual Competidor Competidor { get; set; }
    }
}
